-- Tipos de pan
CREATE TABLE tipos_pan (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ¡Esta es la forma moderna!
    codigo VARCHAR(10) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    activo BOOLEAN DEFAULT true
);

-- Panaderos
CREATE TABLE panaderos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
	telefono VARCHAR(20) NOT NULL,
    activo BOOLEAN DEFAULT true
);

-- Turnos
CREATE TABLE turnos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,  -- 'Madrugada', 'Tarde',
    fecha DATE NOT NULL           
);

-- Pedidos
CREATE TABLE pedidos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turno_id INT NOT NULL REFERENCES turnos(id) ON DELETE CASCADE
);

-- Detalle del pedido por panadero
CREATE TABLE pedido_detalle (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id INT NOT NULL REFERENCES pedidos(id) ON DELETE CASCADE,
    panadero_id INT NOT NULL REFERENCES panaderos(id),
    tipo_pan_id INT NOT NULL REFERENCES tipos_pan(id),
    cantidad INT NOT NULL DEFAULT 0,
    nota TEXT  -- Para los comentarios extra del jefe
);
